platform :ios, '7.0'
inhibit_all_warnings!
pod 'DTCoreText'
pod 'TPKeyboardAvoiding'
pod 'ObjectiveSugar'
pod 'AFNetworking', '~> 2.0'
pod 'SVProgressHUD'
pod 'Appirater'
pod 'TMCache'
pod 'TestFlightSDK'
pod 'Dropbox-Sync-API-SDK'
pod 'GRMustache'
pod 'CorePlot'
